from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class BaseAdapter(Protocol):
    def speak(self, text: str) -> None: ...
    def stop_speak(self) -> None: ...
    def play(self, uri: str) -> None: ...
    def stop_play(self) -> None: ...
    def ring(self) -> None: ...
    def hangup(self) -> None: ...
    def push_digit(self, digit: str) -> None: ...